# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 577)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.blur = QtWidgets.QPushButton(self.centralwidget)
        self.blur.setGeometry(QtCore.QRect(10, 10, 211, 28))
        self.blur.setObjectName("blur")

        self.sepia = QtWidgets.QPushButton(self.centralwidget)
        self.sepia.setGeometry(QtCore.QRect(10, 50, 211, 28))
        self.sepia.setObjectName("sepia")

        self.gray = QtWidgets.QPushButton(self.centralwidget)
        self.gray.setGeometry(QtCore.QRect(10, 90, 211, 28))
        self.gray.setObjectName("gray")

        self.sharpen = QtWidgets.QPushButton(self.centralwidget)
        self.sharpen.setGeometry(QtCore.QRect(10, 130, 211, 28))
        self.sharpen.setObjectName("sharpen")

        self.unsharpen = QtWidgets.QPushButton(self.centralwidget)
        self.unsharpen.setGeometry(QtCore.QRect(10, 170, 211, 28))
        self.unsharpen.setObjectName("unsharpen")

        self.smooth = QtWidgets.QPushButton(self.centralwidget)
        self.smooth.setGeometry(QtCore.QRect(10, 210, 211, 28))
        self.smooth.setObjectName("smooth")

        self.media = QtWidgets.QPushButton(self.centralwidget)
        self.media.setGeometry(QtCore.QRect(10, 250, 211, 28))
        self.media.setObjectName("media")

        self.emboss = QtWidgets.QPushButton(self.centralwidget)
        self.emboss.setGeometry(QtCore.QRect(10, 290, 211, 28))
        self.emboss.setObjectName("emboss")

        self.find_egde = QtWidgets.QPushButton(self.centralwidget)
        self.find_egde.setGeometry(QtCore.QRect(10, 330, 211, 28))
        self.find_egde.setObjectName("find_egde")

        self.enhance_edge = QtWidgets.QPushButton(self.centralwidget)
        self.enhance_edge.setGeometry(QtCore.QRect(10, 370, 211, 28))
        self.enhance_edge.setObjectName("enhance_edge")

        self.histogram = QtWidgets.QPushButton(self.centralwidget)
        self.histogram.setGeometry(QtCore.QRect(10, 490, 211, 28))
        self.histogram.setObjectName("histogram")

        self.normalization = QtWidgets.QPushButton(self.centralwidget)
        self.normalization.setGeometry(QtCore.QRect(10, 450, 211, 28))
        self.normalization.setObjectName("normalization")

        self.crop = QtWidgets.QPushButton(self.centralwidget)
        self.crop.setGeometry(QtCore.QRect(10, 410, 211, 28))
        self.crop.setObjectName("crop")

        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(240, 10, 821, 501))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.image.setFont(font)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("duck.jpg"))
        self.image.setScaledContents(True)
        self.image.setObjectName("image")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actioncredits = QtWidgets.QAction(MainWindow)
        self.actioncredits.setObjectName("actioncredits")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionsave)
        self.menuhelp.addAction(self.actioncredits)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.blur.setText(_translate("MainWindow", "blur"))
        self.sepia.setText(_translate("MainWindow", "sepia"))
        self.gray.setText(_translate("MainWindow", "gray scale"))
        self.sharpen.setText(_translate("MainWindow", "sharpen"))
        self.unsharpen.setText(_translate("MainWindow", "unsharpen"))
        self.smooth.setText(_translate("MainWindow", "smooth"))
        self.media.setText(_translate("MainWindow", "median"))
        self.emboss.setText(_translate("MainWindow", "emboss"))
        self.find_egde.setText(_translate("MainWindow", "find edegs"))
        self.enhance_edge.setText(_translate("MainWindow", "enhance edges"))
        self.histogram.setText(_translate("MainWindow", "color histogram"))
        self.normalization.setText(_translate("MainWindow", "image normalization"))
        self.crop.setText(_translate("MainWindow", "crop"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionopen.setText(_translate("MainWindow", "open.."))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actioncredits.setText(_translate("MainWindow", "credits"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
